gems:
- facets ~>2.4.0
- shenandoah =0.0.0
- haml ~>2.2.0
- json_pure
- rest-client
- buildr-iidea 0.0.7
jruby: 1.4.0 # Oddly, this does not require that jruby 1.4.0 be installed -- just that _some_ version be installed
ant: 1.7.0
