gems:
- buildr ~>1.4.4
- facets ~>2.4.0
- haml ~>2.2.0
- shenandoah =0.0.0
- json_pure
- rest-client
- buildr-iidea 0.0.8
jruby: 1.5.6 # Oddly, this does not require that jruby 1.5.6 be installed -- just that _some_ version be installed
ant: 1.7.0
