-- This down script reverts enough of the changes to CSM that the corresponding
-- up script can be run again.  It does not fully revert to CSM 3.2.

DROP TABLE CSM_FILTER_CLAUSE;
DROP SEQUENCE CSM_FILTER_CLAUSE_FILTE_ID_SEQ;

CREATE SEQUENCE CSM_PG_PE_ID_SEQ;
ALTER TABLE CSM_PG_PE ALTER COLUMN PG_PE_ID SET DEFAULT nextval('CSM_PG_PE_ID_SEQ');
DROP SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ;

CREATE SEQUENCE CSM_ROLE_PRIV_SEQ;
ALTER TABLE CSM_ROLE_PRIVILEGE ALTER COLUMN ROLE_PRIVILEGE_ID SET DEFAULT nextval('CSM_ROLE_PRIV_SEQ');
DROP SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ;

CREATE SEQUENCE CSM_USER_GROUP_ID_SEQ;
ALTER TABLE CSM_USER_GROUP ALTER COLUMN USER_GROUP_ID SET DEFAULT nextval('CSM_USER_GROUP_ID_SEQ');
DROP SEQUENCE CSM_USER_GROU_USER_GROUP_I_SEQ;

DROP TABLE CSM_MAPPING;
DROP SEQUENCE CSM_MAPPING_MAPPING_SEQ;
