class AddMoreUniqueConstraints extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
        execute("ALTER TABLE sites ADD CONSTRAINT un_site_name UNIQUE (name)")
        execute("ALTER TABLE sites ADD CONSTRAINT un_site_assigned_id UNIQUE (assigned_identifier)")

        execute("ALTER TABLE activities ADD CONSTRAINT un_activity_code UNIQUE (code, source_id)")
        execute("ALTER TABLE activities ADD CONSTRAINT un_activity_name UNIQUE (name, source_id)")
        execute("ALTER TABLE sources ADD CONSTRAINT un_source_name UNIQUE (name)")

        execute("ALTER TABLE studies ADD CONSTRAINT un_study_assigned_id UNIQUE (assigned_identifier)")
        execute("ALTER TABLE study_sites ADD CONSTRAINT un_study_site_components UNIQUE (study_id, site_id)")
        execute("ALTER TABLE subject_assignments ADD CONSTRAINT un_study_site_subject UNIQUE (study_site_id, subject_id)")
        execute("ALTER TABLE users ADD CONSTRAINT un_user_name UNIQUE (name)")
        execute("ALTER TABLE users ADD CONSTRAINT un_user_csm_user UNIQUE (csm_user_id)")

        execute("ALTER TABLE activities                ADD CONSTRAINT un_activity_grid_id        UNIQUE (grid_id)")
        execute("ALTER TABLE adverse_events            ADD CONSTRAINT un_ae_grid_id              UNIQUE (grid_id)")
        execute("ALTER TABLE ae_notifications          ADD CONSTRAINT un_ae_notice_grid_id       UNIQUE (grid_id)")
        execute("ALTER TABLE amendment_approvals       ADD CONSTRAINT un_amendt_apprv_grid_id    UNIQUE (grid_id)")
        execute("ALTER TABLE amendments                ADD CONSTRAINT un_amendment_grid_id       UNIQUE (grid_id)")
        execute("ALTER TABLE changes                   ADD CONSTRAINT un_change_grid_id          UNIQUE (grid_id)")
        execute("ALTER TABLE deltas                    ADD CONSTRAINT un_delta_grid_id           UNIQUE (grid_id)")
        execute("ALTER TABLE epochs                    ADD CONSTRAINT un_epoch_grid_id           UNIQUE (grid_id)")
        execute("ALTER TABLE holidays                  ADD CONSTRAINT un_blackout_grid_id        UNIQUE (grid_id)")
        execute("ALTER TABLE periods                   ADD CONSTRAINT un_period_grid_id          UNIQUE (grid_id)")
        execute("ALTER TABLE planned_activities        ADD CONSTRAINT un_plnd_act_grid_id        UNIQUE (grid_id)")
        execute("ALTER TABLE planned_calendars         ADD CONSTRAINT un_plnd_cal_grid_id        UNIQUE (grid_id)")
        execute("ALTER TABLE populations               ADD CONSTRAINT un_pop_grid_id             UNIQUE (grid_id)")
        execute("ALTER TABLE scheduled_activities      ADD CONSTRAINT un_sched_act_grid_id       UNIQUE (grid_id)")
        execute("ALTER TABLE scheduled_activity_states ADD CONSTRAINT un_sched_act_state_grid_id UNIQUE (grid_id)")
        execute("ALTER TABLE scheduled_calendars       ADD CONSTRAINT un_sched_cal_grid_id       UNIQUE (grid_id)")
        execute("ALTER TABLE scheduled_study_segments  ADD CONSTRAINT un_sched_segmt_grid_id     UNIQUE (grid_id)")
        execute("ALTER TABLE sites                     ADD CONSTRAINT un_site_grid_id            UNIQUE (grid_id)")
        execute("ALTER TABLE sources                   ADD CONSTRAINT un_source_grid_id          UNIQUE (grid_id)")
        execute("ALTER TABLE studies                   ADD CONSTRAINT un_study_grid_id           UNIQUE (grid_id)")
        execute("ALTER TABLE study_segments            ADD CONSTRAINT un_segment_grid_id         UNIQUE (grid_id)")
        execute("ALTER TABLE study_sites               ADD CONSTRAINT un_study_site_grid_id      UNIQUE (grid_id)")
        execute("ALTER TABLE subject_assignments       ADD CONSTRAINT un_subj_assign_grid_id     UNIQUE (grid_id)")
        execute("ALTER TABLE subjects                  ADD CONSTRAINT un_subject_grid_id         UNIQUE (grid_id)")
        execute("ALTER TABLE users                     ADD CONSTRAINT un_user_grid_id            UNIQUE (grid_id)")
    }

    void down() {
        execute("ALTER TABLE sites DROP CONSTRAINT un_site_name")
        execute("ALTER TABLE sites DROP CONSTRAINT un_site_assigned_id")

        execute("ALTER TABLE activities DROP CONSTRAINT un_activity_code")
        execute("ALTER TABLE activities DROP CONSTRAINT un_activity_name")
        execute("ALTER TABLE sources DROP CONSTRAINT un_source_name")

        execute("ALTER TABLE studies DROP CONSTRAINT un_study_assigned_id")
        execute("ALTER TABLE study_sites DROP CONSTRAINT un_study_site_components")
        execute("ALTER TABLE subject_assignments DROP CONSTRAINT un_study_site_subject")
        execute("ALTER TABLE users DROP CONSTRAINT un_user_name")
        execute("ALTER TABLE users DROP CONSTRAINT un_user_csm_user")

        execute("ALTER TABLE activities                DROP CONSTRAINT un_activity_grid_id")
        execute("ALTER TABLE adverse_events            DROP CONSTRAINT un_ae_grid_id")
        execute("ALTER TABLE ae_notifications          DROP CONSTRAINT un_ae_notice_grid_id")
        execute("ALTER TABLE amendment_approvals       DROP CONSTRAINT un_amendt_apprv_grid_id")
        execute("ALTER TABLE amendments                DROP CONSTRAINT un_amendment_grid_id")
        execute("ALTER TABLE changes                   DROP CONSTRAINT un_change_grid_id")
        execute("ALTER TABLE deltas                    DROP CONSTRAINT un_delta_grid_id")
        execute("ALTER TABLE epochs                    DROP CONSTRAINT un_epoch_grid_id")
        execute("ALTER TABLE holidays                  DROP CONSTRAINT un_blackout_grid_id")
        execute("ALTER TABLE periods                   DROP CONSTRAINT un_period_grid_id")
        execute("ALTER TABLE planned_activities        DROP CONSTRAINT un_plnd_act_grid_id")
        execute("ALTER TABLE planned_calendars         DROP CONSTRAINT un_plnd_cal_grid_id")
        execute("ALTER TABLE populations               DROP CONSTRAINT un_pop_grid_id")
        execute("ALTER TABLE scheduled_activities      DROP CONSTRAINT un_sched_act_grid_id")
        execute("ALTER TABLE scheduled_activity_states DROP CONSTRAINT un_sched_act_state_grid_id")
        execute("ALTER TABLE scheduled_calendars       DROP CONSTRAINT un_sched_cal_grid_id")
        execute("ALTER TABLE scheduled_study_segments  DROP CONSTRAINT un_sched_segmt_grid_id")
        execute("ALTER TABLE sites                     DROP CONSTRAINT un_site_grid_id")
        execute("ALTER TABLE sources                   DROP CONSTRAINT un_source_grid_id")
        execute("ALTER TABLE studies                   DROP CONSTRAINT un_study_grid_id")
        execute("ALTER TABLE study_segments            DROP CONSTRAINT un_segment_grid_id")
        execute("ALTER TABLE study_sites               DROP CONSTRAINT un_study_site_grid_id")
        execute("ALTER TABLE subject_assignments       DROP CONSTRAINT un_subj_assign_grid_id")
        execute("ALTER TABLE subjects                  DROP CONSTRAINT un_subject_grid_id")
        execute("ALTER TABLE users                     DROP CONSTRAINT un_user_grid_id")
    }
}
