source :rubygems

gem 'faraday', '~> 0.6.1'
gem 'nokogiri'
gem 'builder', '~> 3.0.0'

group :development do
  gem 'rspec', '~> 2.5'
  gem 'webmock'
  # Ref: https://github.com/sporkmonger/addressable/pull/33
  gem 'addressable', '2.2.4'
end
