package edu.northwestern.bioinformatics.studycalendar.grid.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class StudyServiceImpl extends StudyServiceImplBase {

	
	public StudyServiceImpl() throws RemoteException {
		super();
	}
	

	public edu.northwestern.bioinformatics.studycalendar.grid.Study retrieveStudyByAssignedIdentifier(java.lang.String assignedIdentifier) throws RemoteException, edu.northwestern.bioinformatics.studycalendar.grid.stubs.types.StudyDoesNotExists {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

	public edu.northwestern.bioinformatics.studycalendar.grid.Study createStudy(edu.northwestern.bioinformatics.studycalendar.grid.Study study) throws RemoteException, edu.northwestern.bioinformatics.studycalendar.grid.stubs.types.StudyAlreadyException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}

